"""initial schema

Revision ID: 31d35468f06c
Revises: 
Create Date: 2026-09-04 02:22:23.984091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d35468f06c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('analysis_window_days', sa.Integer(), nullable=False),
    sa.Column('churn_threshold_medium', sa.Integer(), nullable=False),
    sa.Column('churn_threshold_high', sa.Integer(), nullable=False),
    sa.Column('churn_threshold_critical', sa.Integer(), nullable=False),
    sa.Column('campaign_cooldown_days', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_category_business_name')
    )
    op.create_index(op.f('ix_categories_business_id'), 'categories', ['business_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preferred_channel', sa.Enum('email', 'whatsapp', 'sms', 'internal', name='channel'), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='customer_status'), nullable=False),
    sa.Column('last_purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_ticket', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_interval_days', sa.Integer(), nullable=True),
    sa.Column('segment', sa.Enum('vip', 'loyal', 'frequent', 'new', 'potential', 'at_risk', 'dormant', 'lost', 'high_value', 'low_value', name='customer_segment'), nullable=False),
    sa.Column('customer_value', sa.Enum('low', 'medium', 'high', name='customer_value'), nullable=False),
    sa.Column('activity_status', sa.Enum('active', 'at_risk', 'dormant', 'lost', name='activity_status'), nullable=False),
    sa.Column('rfm_recency_days', sa.Integer(), nullable=False),
    sa.Column('rfm_frequency', sa.Integer(), nullable=False),
    sa.Column('rfm_monetary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rfm_r', sa.Integer(), nullable=False),
    sa.Column('rfm_f', sa.Integer(), nullable=False),
    sa.Column('rfm_m', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'email', name='uq_customer_business_email')
    )
    op.create_index(op.f('ix_customers_activity_status'), 'customers', ['activity_status'], unique=False)
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_segment'), 'customers', ['segment'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('training', 'candidate', 'production', 'deprecated', 'failed', name='model_status'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_business_id'), 'model_versions', ['business_id'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_business_id'), 'rules', ['business_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'business_user', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('customers', 'products', 'sales', name='import_type'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('accepted_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_confirmation', 'confirmed', 'cancelled', name='import_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_business_id'), 'imports', ['business_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_model_version_id'), 'model_metrics', ['model_version_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=False),
    sa.Column('churn_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risk_level'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('expected_next_purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_until_expected_purchase', sa.Integer(), nullable=True),
    sa.Column('purchase_probability', sa.Float(), nullable=True),
    sa.Column('prediction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_business_id'), 'predictions', ['business_id'], unique=False)
    op.create_index(op.f('ix_predictions_customer_id'), 'predictions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_predictions_risk_level'), 'predictions', ['risk_level'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='product_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'sku', name='uq_product_business_sku')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'sms', 'internal', name='sale_channel'), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'digital_wallet', 'other', name='payment_method'), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_business_id'), 'sales', ['business_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('segment', sa.Enum('vip', 'loyal', 'frequent', 'new', 'potential', 'at_risk', 'dormant', 'lost', 'high_value', 'low_value', name='campaign_segment'), nullable=True),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'sms', 'internal', name='campaign_channel'), nullable=False),
    sa.Column('offer', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'active', 'paused', 'finished', 'cancelled', name='campaign_status'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_business_id'), 'campaigns', ['business_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_import_id'), 'import_errors', ['import_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('method', sa.Enum('rules', 'collaborative_filtering', 'frequency', 'cold_start', name='recommendation_method'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_business_id'), 'recommendations', ['business_id'], unique=False)
    op.create_index(op.f('ix_recommendations_customer_id'), 'recommendations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recommendations_product_id'), 'recommendations', ['product_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('recommended_product_id', sa.String(length=36), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('recovery_probability', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=20), nullable=False),
    sa.Column('recommended_offer', sa.String(length=100), nullable=False),
    sa.Column('recommended_timing', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('cooldown_ok', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_business_id'), 'strategies', ['business_id'], unique=False)
    op.create_index(op.f('ix_strategies_customer_id'), 'strategies', ['customer_id'], unique=False)
    op.create_index(op.f('ix_strategies_priority_score'), 'strategies', ['priority_score'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'opened', 'responded', 'converted', 'excluded_no_consent', 'excluded_cooldown', name='recipient_status'), nullable=False),
    sa.Column('recovered_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_customer_id'), 'campaign_recipients', ['customer_id'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'sms', 'internal', name='communication_channel'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_business_id'), 'communications', ['business_id'], unique=False)
    op.create_index(op.f('ix_communications_customer_id'), 'communications', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communications_customer_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_business_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_campaign_recipients_customer_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_strategies_priority_score'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_customer_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_business_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_recommendations_product_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_customer_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_business_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_import_errors_import_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_business_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_business_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_predictions_risk_level'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_customer_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_business_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_model_metrics_model_version_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_imports_business_id'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rules_business_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_business_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_customers_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_activity_status'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_business_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('businesses')
    # ### end Alembic commands ###
